[package]
name = "plateau_drone_gif"
version = "0.2.0"
edition = "2021"
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
image = "0.25"
png = { workspace = true }
rne_assets = { workspace = true }
rne_core = { workspace = true }
rne_data = { workspace = true }
rne_ecs = { workspace = true }
rne_math = { workspace = true }
rne_physics = { workspace = true }
rne_physics_rapier = { workspace = true }
rne_plateau = { workspace = true }
rne_render = { workspace = true }
rne_render_wgpu = { workspace = true, features = ["viewer"] }
rne_robot = { workspace = true }
rne_sensor = { workspace = true }
rne_traffic = { workspace = true }
rne_world = { workspace = true }
uuid = { workspace = true }

[[example]]
name = "46_plateau_drone_gif"
path = "main.rs"
