[package]
name = "go2_door"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
png = { workspace = true }
rne_ai = { workspace = true }
rne_data = { workspace = true }
rne_math = { workspace = true }
rne_nav = { workspace = true }
rne_sensor = { workspace = true }
rne_slam = { workspace = true }
rne_world = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
rne_physics = { workspace = true }
rne_render = { workspace = true }
rne_render_wgpu = { workspace = true, features = ["viewer"] }

[[example]]
name = "132_go2_door"
path = "main.rs"
