//! Optimizes a Unitree G1 backflip over a fixed contact sequence with the native
//! FDDP solver.
//!
//! The sequence is crouch (both feet) -> push (both feet) -> flight (no
//! contacts). The flight cost drives the base yaw coordinate through a full
//! `-2*pi` rotation while tracking a ballistic height arc, and the terminal cost
//! asks for a landed pose at the start height.
//!
//! The floating base composes as `base_world = R_euler * R_x(-90)`, so a
//! rotation about the world lateral (Z) axis — a backflip — is a continuous
//! change of the base **yaw** coordinate and does not enter the Euler
//! singularity (`rne_dynamics::base_velocity_map` inverts the Euler-rate map,
//! which is regular for a yaw rotation). The native `rne_oc` integrator now
//! routes the body twist through that map (`rne_dynamics::integrate_configuration`),
//! so the plan and the dynamics share one chart. See example 114 for a
//! render-only kinematic reference animation.
//!
//! Run with `cargo run --release -p g1_backflip --example 113_g1_backflip`.

use rne_dynamics::{centroidal_momentum, ArticulatedModel, ContactSpec};
use rne_ecs::World;
use rne_math::{Quat, Vec3};
use rne_oc::{
    solve, solve_multiple_shooting, ContactPhase, ContactSequenceDynamics, CostDerivatives,
    CostModel, DdpConfig, MultipleShootingConfig, PhaseCostSchedule, QuadraticCost,
    ShootingDynamics, TerminalDerivatives,
};
use rne_robot::{FloatingBase, Transform3};

const G1_URDF: &str = include_str!("../../assets/robots/g1_description/g1_23dof.urdf");
const BASE_ROTATION_X_RAD: f64 = -std::f64::consts::FRAC_PI_2;
const SOLE_OFFSET_LOCAL_M: Vec3 = Vec3::new(0.0, 0.0, -0.035);
/// Toe contact, forward of the sole in the foot frame. The push phase uses it
/// instead of the full sole so the ankle can plantarflex and the heel can lift.
const TOE_OFFSET_LOCAL_M: Vec3 = Vec3::new(0.09, 0.0, -0.035);
const FOOT_LINKS: [&str; 2] = ["left_ankle_roll_link", "right_ankle_roll_link"];

const STEP_TIME_S: f64 = 0.03;
const BASE_START_Y_M: f64 = 0.82;
const CROUCH_Y_M: f64 = 0.66;
const TARGET_APEX_Y_M: f64 = 1.05;

fn dof_joint_names(model: &ArticulatedModel) -> Vec<String> {
    model
        .kinematic()
        .movable_joint_entities()
        .iter()
        .map(|joint| {
            let child = model.kinematic().joint_child_link(*joint).expect("child");
            let index = model.kinematic().link_index(child).expect("index");
            model
                .kinematic()
                .link_name(index)
                .expect("name")
                .to_string()
        })
        .collect()
}

fn side_sign(name: &str) -> f64 {
    if name.contains("left") {
        1.0
    } else if name.contains("right") {
        -1.0
    } else {
        0.0
    }
}

fn stand_angle(name: &str) -> f64 {
    if name.contains("hip_pitch") {
        -0.18
    } else if name.contains("hip_roll") {
        0.05 * side_sign(name)
    } else if name.contains("knee") {
        0.36
    } else if name.contains("ankle_pitch") {
        -0.18
    } else if name.contains("ankle_roll") {
        -0.03 * side_sign(name)
    } else if name.contains("shoulder_roll") {
        0.20 * side_sign(name)
    } else if name.contains("elbow") {
        0.42
    } else {
        0.0
    }
}

fn crouch_angle(name: &str) -> f64 {
    if name.contains("hip_pitch") {
        -0.55
    } else if name.contains("knee") {
        1.05
    } else if name.contains("ankle_pitch") {
        -0.50
    } else {
        stand_angle(name)
    }
}

fn tuck_angle(name: &str) -> f64 {
    if name.contains("hip_pitch") {
        -1.05
    } else if name.contains("knee") {
        1.75
    } else if name.contains("ankle_pitch") {
        -0.55
    } else if name.contains("shoulder_pitch") {
        -0.60
    } else if name.contains("elbow") {
        0.90
    } else {
        stand_angle(name)
    }
}

fn torque_limit(name: &str) -> f64 {
    if name.contains("knee") {
        139.0
    } else if name.contains("ankle") {
        35.0
    } else if name.contains("shoulder") || name.contains("elbow") || name.contains("wrist") {
        25.0
    } else {
        88.0
    }
}

/// Wraps a phase cost schedule and adds a Boston Dynamics-style centroidal
/// angular-momentum term during flight.
///
/// During a flight phase the whole-body angular momentum about the center of
/// mass is (to first order) conserved and set by the takeoff impulse. Tracking a
/// desired value keeps the flip generated by internal leg/arm motion instead of
/// an uncontrolled base reaction, which is what makes the aerial phase
/// well-conditioned. The schedule keeps its analytic derivatives; the momentum
/// term contributes a numerical state gradient and no control gradient (the
/// momentum does not depend on the control at a given state).
struct CentroidalMomentumCost<'a> {
    model: &'a ArticulatedModel,
    schedule: PhaseCostSchedule,
    flight_start: usize,
    weight: f64,
    desired_angular_momentum_z: f64,
}

impl CentroidalMomentumCost<'_> {
    fn angular_momentum_z(&self, state: &[f64]) -> f64 {
        let nv = state.len() / 2;
        let (q, qd) = state.split_at(nv);
        match centroidal_momentum(self.model, q, qd) {
            Ok(momentum) => momentum[5],
            Err(_) => 0.0,
        }
    }

    fn momentum_term(&self, node: usize, state: &[f64]) -> f64 {
        if node < self.flight_start {
            return 0.0;
        }
        let error = self.angular_momentum_z(state) - self.desired_angular_momentum_z;
        0.5 * self.weight * error * error
    }
}

impl CostModel for CentroidalMomentumCost<'_> {
    fn running(&self, node: usize, state: &[f64], control: &[f64]) -> f64 {
        self.schedule.running(node, state, control) + self.momentum_term(node, state)
    }

    fn terminal(&self, state: &[f64]) -> f64 {
        self.schedule.terminal(state)
    }

    fn running_derivatives(&self, node: usize, state: &[f64], control: &[f64]) -> CostDerivatives {
        let mut derivatives = self.schedule.running_derivatives(node, state, control);
        if node < self.flight_start {
            return derivatives;
        }
        let nv = state.len() / 2;
        let epsilon = 1.0e-6;
        for index in 0..nv {
            let mut plus = state.to_vec();
            plus[index] += epsilon;
            let mut minus = state.to_vec();
            minus[index] -= epsilon;
            let slope = (self.momentum_term(node, &plus) - self.momentum_term(node, &minus))
                / (2.0 * epsilon);
            derivatives.lx[index] += slope;
        }
        derivatives
    }

    fn terminal_derivatives(&self, state: &[f64]) -> TerminalDerivatives {
        self.schedule.terminal_derivatives(state)
    }
}

/// Outcome of one contact-schedule solve.
struct PlanOutcome {
    gap: f64,
    cost: f64,
    jump: f64,
    span: f64,
}

fn main() {
    let document = rne_urdf_import::parse_urdf_document(G1_URDF).expect("parse G1 URDF");
    let mut world = World::new();
    let config = rne_urdf_import::UrdfSpawnConfig {
        attach_colliders: false,
        attach_mesh_colliders: false,
        self_collisions: false,
        use_declared_inertial_masses: true,
        ..rne_urdf_import::UrdfSpawnConfig::default()
    };
    let spawned = rne_urdf_import::spawn_urdf_document_with_config(&mut world, &document, config)
        .expect("spawn G1");
    world.entity_mut(spawned.base_link).insert((
        Transform3::from_translation_rotation(
            Vec3::ZERO,
            Quat::from_rotation_x(BASE_ROTATION_X_RAD),
        ),
        FloatingBase,
    ));
    let model = ArticulatedModel::from_robot(&world, spawned.robot).expect("model");
    let nv = model.nv();
    let control_dim = nv - model.base_dof();
    let joint_names = dof_joint_names(&model);
    assert_eq!(control_dim, 23, "expected 23 actuated G1 joints");

    let mut initial = vec![0.0; 2 * nv];
    initial[1] = BASE_START_Y_M;
    for (dof, name) in joint_names.iter().enumerate() {
        initial[6 + dof] = stand_angle(name);
    }

    let contacts: Vec<ContactSpec> = FOOT_LINKS
        .iter()
        .filter_map(|name| {
            model
                .kinematic()
                .link_entity_by_name(name)
                .map(|link| ContactSpec {
                    link,
                    point_local_m: SOLE_OFFSET_LOCAL_M,
                })
        })
        .collect();
    assert_eq!(contacts.len(), 2, "expected two foot contacts");
    // The push rolls onto the toes so the ankle can extend and launch.
    let toe_contacts: Vec<ContactSpec> = FOOT_LINKS
        .iter()
        .filter_map(|name| {
            model
                .kinematic()
                .link_entity_by_name(name)
                .map(|link| ContactSpec {
                    link,
                    point_local_m: TOE_OFFSET_LOCAL_M,
                })
        })
        .collect();
    assert_eq!(toe_contacts.len(), 2, "expected two toe contacts");
    let mut crouch_steps = 8_usize;
    let mut push_steps = 6_usize;
    let mut flight_steps = 22_usize;
    let mut target_apex_y_m = TARGET_APEX_Y_M;
    let mut search = false;
    let mut args = std::env::args().skip(1);
    while let Some(arg) = args.next() {
        let mut value = || args.next().and_then(|v| v.parse::<usize>().ok());
        match arg.as_str() {
            "--crouch" => crouch_steps = value().unwrap_or(crouch_steps),
            "--push" => push_steps = value().unwrap_or(push_steps),
            "--flight" => flight_steps = value().unwrap_or(flight_steps),
            "--apex" => {
                target_apex_y_m = args
                    .next()
                    .and_then(|v| v.parse::<f64>().ok())
                    .unwrap_or(target_apex_y_m)
            }
            "--search" => search = true,
            _ => {}
        }
    }
    let no_flip = std::env::var("G1_NO_FLIP").is_ok();
    let use_multiple_shooting = std::env::var("G1_SOLVER")
        .map(|value| value == "ms")
        .unwrap_or(false);
    let use_exact_hessian = std::env::var("G1_EXACT_HESSIAN").is_ok();
    let run_plan = |crouch_steps: usize,
                    push_steps: usize,
                    flight_steps: usize,
                    target_apex_y_m: f64|
     -> PlanOutcome {
    let horizon = crouch_steps + push_steps + flight_steps;
    println!("g1 backflip FDDP probe: nv={nv} control_dim={control_dim} horizon={horizon}");

    let phases = [
        ContactPhase {
            contacts: toe_contacts.clone(),
            steps: crouch_steps,
        },
        ContactPhase {
            contacts: toe_contacts.clone(),
            steps: push_steps,
        },
        ContactPhase {
            contacts: Vec::new(),
            steps: flight_steps,
        },
    ];
    let dynamics = ContactSequenceDynamics::new(&model, STEP_TIME_S, &phases);

    let control_weights = vec![2.0e-4; control_dim];
    let zero = vec![0.0; 2 * nv];
    let mut running = Vec::with_capacity(horizon);
    for node in 0..horizon {
        let mut weights = vec![0.0; 2 * nv];
        let mut reference = vec![0.0; 2 * nv];
        if node < crouch_steps {
            weights[1] = 300.0;
            reference[1] = CROUCH_Y_M;
        }
        for (dof, name) in joint_names.iter().enumerate() {
            if node < crouch_steps {
                weights[6 + dof] = 8.0;
                reference[6 + dof] = crouch_angle(name);
            } else if node < crouch_steps + push_steps {
                weights[6 + dof] = 3.0;
                reference[6 + dof] = stand_angle(name);
            } else {
                weights[6 + dof] = 2.0;
                reference[6 + dof] = tuck_angle(name);
            }
        }
        if node >= crouch_steps + push_steps {
            let flight = (node - crouch_steps - push_steps) as f64;
            let t = flight / flight_steps as f64;
            // Ballistic height arc and a full backward rotation of the base yaw.
            let arc = (std::f64::consts::PI * t).sin();
            weights[1] = 400.0;
            reference[1] = BASE_START_Y_M + (target_apex_y_m - BASE_START_Y_M) * arc;
            if !no_flip {
                weights[5] = 400.0;
                reference[5] = -2.0 * std::f64::consts::PI * t;
            }
        }
        let mut cost = QuadraticCost::new(weights, control_weights.clone(), zero.clone());
        cost.state_reference = reference;
        cost.running_scale = 1.0;
        running.push(cost);
    }

    let mut terminal_weights = vec![0.0; 2 * nv];
    terminal_weights[1] = 4.0e3;
    if !no_flip {
        terminal_weights[5] = 1.0e3;
    }
    for index in 0..6 {
        terminal_weights[nv + index] = 40.0;
    }
    for (dof, name) in joint_names.iter().enumerate() {
        // The wrist joints have low torque authority, so a hard zero terminal
        // velocity is not achievable in the last step and leaves a residual
        // gap. Ask for a soft stop there and a firm stop on the body.
        terminal_weights[nv + 6 + dof] = if name.contains("wrist") { 5.0 } else { 40.0 };
    }
    let mut terminal = QuadraticCost::new(zero.clone(), vec![0.0; control_dim], terminal_weights);
    let mut terminal_reference = vec![0.0; 2 * nv];
    terminal_reference[1] = BASE_START_Y_M;
    terminal_reference[5] = -2.0 * std::f64::consts::PI;
    for (dof, name) in joint_names.iter().enumerate() {
        terminal_reference[6 + dof] = stand_angle(name);
    }
    terminal.state_reference = terminal_reference;
    let schedule = PhaseCostSchedule { running, terminal };

    // Warm start: a crouch pose held, then a tucked spin through flight.
    let mut crouch = initial.clone();
    crouch[1] = CROUCH_Y_M;
    for (dof, name) in joint_names.iter().enumerate() {
        crouch[6 + dof] = crouch_angle(name);
    }
    // Launch velocity implied by the ballistic arc: the vertical speed needed
    // at takeoff to reach the apex over the flight time.
    let flight_time_s = flight_steps as f64 * STEP_TIME_S;
    let launch_velocity_m_s = 2.0 * (target_apex_y_m - BASE_START_Y_M) / flight_time_s;
    let mut states = Vec::with_capacity(horizon + 1);
    for node in 0..=horizon {
        let mut state = if node < crouch_steps {
            crouch.clone()
        } else if node < crouch_steps + push_steps {
            let push = (node - crouch_steps) as f64;
            let linear = (push + 1.0) / push_steps as f64;
            // Ease-out so the joint velocity reaches zero at the push-to-flight
            // boundary, matching the flight ease-in and keeping the transition
            // continuous.
            let t = linear * linear * (3.0 - 2.0 * linear);
            let mut extended = initial.clone();
            extended[1] = BASE_START_Y_M + 0.05 * linear.sin();
            extended[nv + 1] = launch_velocity_m_s;
            for (dof, name) in joint_names.iter().enumerate() {
                extended[6 + dof] =
                    stand_angle(name) + (crouch_angle(name) - stand_angle(name)) * (1.0 - t);
            }
            extended
        } else {
            let flight = (node - crouch_steps - push_steps) as f64;
            let t = flight / flight_steps as f64;
            let mut tucked = initial.clone();
            tucked[1] = BASE_START_Y_M
                + (target_apex_y_m - BASE_START_Y_M) * (std::f64::consts::PI * t).sin();
            tucked[5] = -2.0 * std::f64::consts::PI * t;
            // The spin is built during flight; do not impose the full rate at
            // the push boundary, where the planted feet cannot supply it.
            tucked[nv + 5] = -2.0 * std::f64::consts::PI * t / (flight_steps as f64 * STEP_TIME_S);
            // Blend the legs from the push extension into the tuck over the
            // first third of flight so the push-to-flight joint velocity is
            // continuous instead of a step.
            let ramp = (t / 0.33).min(1.0);
            // Ease-in so the joint velocity starts at zero and matches the push
            // ease-out at the boundary.
            let blend = ramp * ramp * (3.0 - 2.0 * ramp);
            for (dof, name) in joint_names.iter().enumerate() {
                let start = stand_angle(name);
                tucked[6 + dof] = start + (tuck_angle(name) - start) * blend;
            }
            tucked
        };
        state[nv + 1] = 0.0;
        states.push(state);
    }
    states[0] = initial.clone();

    let controls = vec![vec![0.0; control_dim]; horizon];
    let limits: Vec<f64> = joint_names.iter().map(|name| torque_limit(name)).collect();
    // FDDP keeps the warm-start gaps open on the first pass, so the kinematic
    // reference can seed a solve that the analytic Jacobians then close.
    let config = DdpConfig {
        max_iterations: 300,
        tolerance: 1.0e-7,
        keep_gaps_open: true,
        control_lower: Some(limits.iter().map(|limit| -limit).collect()),
        control_upper: Some(limits.clone()),
        ..DdpConfig::default()
    };
    println!("solving FDDP...");
    // Target the centroidal angular momentum the warm-start spin already
    // produces at mid-flight, so the aerial phase is shaped toward that flip.
    let flight_axis_momentum = {
        let mid = &states[crouch_steps + push_steps + flight_steps / 2];
        let nv = mid.len() / 2;
        centroidal_momentum(&model, &mid[..nv], &mid[nv..])
            .map(|momentum| momentum[5])
            .unwrap_or(0.0)
    };
    let momentum_weight = std::env::var("G1_MOMENTUM_WEIGHT")
        .ok()
        .and_then(|value| value.parse().ok())
        .unwrap_or(0.0);
    let cost = CentroidalMomentumCost {
        model: &model,
        schedule,
        flight_start: crouch_steps + push_steps,
        weight: momentum_weight,
        desired_angular_momentum_z: flight_axis_momentum,
    };
    println!("momentum: desired L_z={flight_axis_momentum:.3} kg m^2/s weight={momentum_weight}");
    let solution = if use_multiple_shooting {
        let ms_config = MultipleShootingConfig {
            max_iterations: 1000,
            tolerance: 1.0e-4,
            use_exact_hessian,
            control_lower: Some(limits.iter().map(|limit| -limit).collect()),
            control_upper: Some(limits.clone()),
            ..MultipleShootingConfig::default()
        };
        println!("solving multiple shooting (exact_hessian={use_exact_hessian})...");
        solve_multiple_shooting(&dynamics, &cost, &states, &controls, &ms_config).expect("solve")
    } else {
        solve(&dynamics, &cost, &states, &controls, &config).expect("solve")
    };

    let apex_y = solution
        .states
        .iter()
        .fold(f64::MIN, |maximum, state| maximum.max(state[1]));
    let final_y = solution.states.last().expect("states")[1];
    let min_yaw = solution
        .states
        .iter()
        .fold(f64::MAX, |minimum, state| minimum.min(state[5]));
    let max_yaw = solution
        .states
        .iter()
        .fold(f64::MIN, |maximum, state| maximum.max(state[5]));
    let mut max_gap = 0.0_f64;
    let mut failed_nodes = 0_usize;
    let mut worst_node = 0_usize;
    let mut worst_gap = 0.0_f64;
    let mut worst_component = 0_usize;
    for node in 0..horizon {
        match dynamics.step_at(node, &solution.states[node], &solution.controls[node]) {
            Ok(predicted) => {
                for (a, b) in solution.states[node + 1].iter().zip(&predicted) {
                    max_gap = max_gap.max((a - b).abs());
                }
                let mut node_gap = 0.0_f64;
                let mut node_gap_index = 0_usize;
                for (index, (a, b)) in solution.states[node + 1].iter().zip(&predicted).enumerate()
                {
                    if (a - b).abs() > node_gap {
                        node_gap = (a - b).abs();
                        node_gap_index = index;
                    }
                }
                if node_gap > worst_gap {
                    worst_gap = node_gap;
                    worst_node = node;
                    worst_component = node_gap_index;
                }
            }
            Err(_) => failed_nodes += 1,
        }
    }
    let worst_label = if worst_component < nv {
        format!("q[{}]", worst_component)
    } else if worst_component < nv + 6 {
        format!("base_qd[{}]", worst_component - nv)
    } else {
        let joint = worst_component - nv - 6;
        format!(
            "qd[{}] ({})",
            joint,
            joint_names.get(joint).map(String::as_str).unwrap_or("?")
        )
    };
    println!(
        "worst gap {worst_gap:.3e} at node {worst_node} component {worst_component} {worst_label} (crouch<{crouch_steps}, push<{})",
        crouch_steps + push_steps
    );
    let feasible = max_gap < 1.0e-4 && failed_nodes == 0;
    println!(
        "converged={} feasible={} cost_finite={}",
        solution.converged,
        feasible,
        solution.cost.is_finite(),
    );
    let max_torque = solution
        .controls
        .iter()
        .flatten()
        .fold(0.0_f64, |maximum, value| maximum.max(value.abs()));
    println!(
        "cost={:.4} apex_y={apex_y:.3} final_y={final_y:.3} jump={:.3} yaw=[{min_yaw:.2},{max_yaw:.2}] span={:.2} rad max_gap={max_gap:.2e} max_torque={max_torque:.1} iterations={}",
        solution.cost,
        apex_y - BASE_START_Y_M,
        max_yaw - min_yaw,
        solution.iterations,
    );
        PlanOutcome {
            gap: max_gap,
            cost: solution.cost,
            jump: apex_y - BASE_START_Y_M,
            span: max_yaw - min_yaw,
        }
    };

    let score = |outcome: &PlanOutcome| outcome.gap + 5.0 * (0.10 - outcome.jump).max(0.0);
    if search {
        let mut best: Option<(PlanOutcome, [usize; 3])> = None;
        for crouch in [6_usize, 8, 10] {
            for push in [5_usize, 6, 7] {
                for flight in [18_usize, 20, 22] {
                    let outcome = run_plan(crouch, push, flight, TARGET_APEX_Y_M);
                    let better = best
                        .as_ref()
                        .map(|(current, _)| score(&outcome) < score(current))
                        .unwrap_or(true);
                    if better {
                        best = Some((outcome, [crouch, push, flight]));
                    }
                }
            }
        }
        if let Some((outcome, schedule)) = best {
            println!(
                "BEST schedule crouch={} push={} flight={} gap={:.3e} cost={:.1} jump={:.3} span={:.2} score={:.3}",
                schedule[0],
                schedule[1],
                schedule[2],
                outcome.gap,
                outcome.cost,
                outcome.jump,
                outcome.span,
                score(&outcome),
            );
        }
    } else {
        let outcome = run_plan(crouch_steps, push_steps, flight_steps, target_apex_y_m);
        println!(
            "RESULT gap={:.3e} cost={:.1} jump={:.3} span={:.2} score={:.3}",
            outcome.gap,
            outcome.cost,
            outcome.jump,
            outcome.span,
            score(&outcome),
        );
    }
}
