[package]
name = "rne_plugin_example_velocity_servo"
description = "Example controller plugin compiled to a loadable shared library"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
rne_plugin_sdk = { workspace = true }
