#!/usr/bin/env bash
# Generates .cargo/config.toml with [patch.crates-io] entries for ROS message crates.
set -eo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROS_PREFIX="${ROS_PREFIX:-/opt/ros/jazzy}"
CONFIG_DIR="${1:-$SCRIPT_DIR/.cargo}"
CONFIG_FILE="$CONFIG_DIR/config.toml"

if [[ ! -d "$ROS_PREFIX/share" ]]; then
  echo "ROS prefix not found: $ROS_PREFIX" >&2
  echo "Set ROS_PREFIX or source your ROS setup.bash first." >&2
  exit 1
fi

mkdir -p "$CONFIG_DIR"

{
  echo '# Generated by generate_cargo_config.sh — do not edit by hand.'
  echo '# Re-run after changing ROS distro or installing new rosidl-generator-rs crates.'
  echo
  echo '[patch.crates-io]'
} >"$CONFIG_FILE"

while IFS= read -r -d '' manifest; do
  crate_name="$(grep -m1 '^name = ' "$manifest" | sed -E 's/^name = "(.*)"$/\1/')"
  crate_dir="$(dirname "$manifest")"
  echo "$crate_name = { path = \"$crate_dir\" }" >>"$CONFIG_FILE"
done < <(find "$ROS_PREFIX/share" -path '*/rust/Cargo.toml' -print0 | sort -z)

echo "Wrote $CONFIG_FILE ($(grep -c ' = { path = ' "$CONFIG_FILE") patches)"
