[package]
name = "rne_mobility_benchmark"
version = "0.2.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
default = []
mujoco = ["dep:rne_physics_mujoco", "rne_physics_mujoco/mujoco"]

[lib]
path = "src/lib.rs"

[[bin]]
name = "rne-mobility-benchmark"
path = "src/main.rs"
doc = false

[dependencies]
anyhow = { workspace = true }
rne_ai = { workspace = true }
rne_core = { workspace = true }
rne_ecs = { workspace = true }
rne_math = { workspace = true }
rne_physics = { workspace = true }
rne_physics_mujoco = { version = "=0.2.0", path = "../../crates/rne_physics_mujoco", optional = true }
rne_physics_rapier = { workspace = true }
rne_robot = { workspace = true }
rne_world = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
