[package]
name = "unitree_g1_dex3_pick_place"
version = "0.2.0"
edition = "2021"
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
rne_ai = { workspace = true }
rne_math = { workspace = true }
rne_render = { workspace = true }
rne_render_wgpu = { workspace = true }
png = { workspace = true }

[[example]]
name = "42_unitree_g1_dex3_pick_place"
path = "main.rs"
