[package]
name = "mobile_manipulator_wrist_cam"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
rne_ai = { workspace = true }

[[example]]
name = "24_mobile_manipulator_wrist_cam"
path = "main.rs"
