[package]
name = "house_3dgs_hybrid"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
png = { workspace = true }
rne_math = { workspace = true }
rne_render = { workspace = true }
rne_render_3dgs = { workspace = true }
rne_render_wgpu = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }

[[example]]
name = "88_house_3dgs_hybrid"
path = "main.rs"

