[package]
name = "go2_velocity_terrain"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
rne_ai = { path = "../../crates/rne_ai" }
rne_math = { path = "../../crates/rne_math" }

[[example]]
name = "65_go2_velocity_terrain"
path = "main.rs"
