[package]
name = "deformable_cloth"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
rne_assets = { workspace = true }
rne_deformable = { workspace = true }
rne_ecs = { workspace = true }
rne_math = { workspace = true }
rne_render = { workspace = true }
rne_render_wgpu = { workspace = true }
rne_world = { workspace = true }

[[example]]
name = "44_deformable_cloth"
path = "main.rs"
