[package]
name = "nav_map_media"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
png = { workspace = true }
rne_math = { workspace = true }
rne_nav = { workspace = true }
rne_render = { workspace = true }
rne_render_wgpu = { workspace = true, features = ["viewer"] }
rne_world = { workspace = true }

[[example]]
name = "121_nav_map_media"
path = "main.rs"
