[package]
name = "control_eval_demo"
version = "0.2.0"
edition = "2021"
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
image = "0.25"
png = { workspace = true }
rne_ai = { workspace = true }
rne_core = { workspace = true }
rne_ecs = { workspace = true }
rne_math = { workspace = true }
rne_physics = { workspace = true }
rne_render = { workspace = true }
rne_render_wgpu = { workspace = true }
rne_robot = { workspace = true }
rne_world = { workspace = true }

[[example]]
name = "50_control_eval"
path = "main.rs"
