[package]
name = "dynamics_diagnostics"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
rne_dynamics = { workspace = true }
rne_ecs = { workspace = true }
rne_robot = { workspace = true }
rne_urdf_import = { workspace = true }

[[example]]
name = "103_dynamics_diagnostics"
path = "main.rs"
