[package]
name = "traffic_city_replay"
version = "0.2.0"
edition = "2021"
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
bevy_ecs = { workspace = true }
rne_core = { workspace = true }
rne_ecs = { workspace = true }
rne_traffic = { workspace = true }
uuid = { workspace = true }

[[example]]
name = "47_traffic_city_replay"
path = "main.rs"
