[package]
name = "urdf_mesh_render"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
rne_ecs = { workspace = true }
rne_math = { workspace = true }
rne_render = { workspace = true }
rne_render_wgpu = { workspace = true, features = ["viewer"] }
rne_urdf_import = { workspace = true }
rne_world = { workspace = true }

[[example]]
name = "09_urdf_mesh_render"
path = "main.rs"
