[package]
name = "go2_fall_vs_save"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
image = "0.25"
png = { workspace = true }
rne_ai = { workspace = true }
rne_math = { workspace = true }
rne_render = { workspace = true }
rne_render_wgpu = { workspace = true, features = ["viewer"] }

[[example]]
name = "52_go2_fall_vs_save"
path = "main.rs"
