[package]
name = "mobile_manipulator_arm"
version = "0.2.0"
edition = "2021"
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
rne_core = { workspace = true }
rne_ecs = { workspace = true }
rne_math = { workspace = true }
rne_physics = { workspace = true }
rne_physics_rapier = { workspace = true }
rne_urdf_import = { workspace = true }
rne_world = { workspace = true }

[[example]]
name = "20_mobile_manipulator_arm"
path = "main.rs"
