[package]
name = "rne_physics"
description = "Physics backend traits and components for Robot Native Engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bevy_ecs = { workspace = true }
rne_core = { workspace = true }
rne_ecs = { workspace = true }
rne_math = { workspace = true }
rne_world = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
approx = "0.5"
