[package]
name = "rne_adapter_ros2"
description = "ROS2 adapter mappings for Robot Native Engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
ros2 = []

[dependencies]
rne_core = { workspace = true }
rne_data = { workspace = true }
rne_math = { workspace = true }
rne_sensor = { workspace = true }
rne_world = { workspace = true }
[dev-dependencies]
approx = "0.5"
