[package]
name = "rne_render_wgpu"
description = "wgpu render backend for Robot Native Engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
viewer = ["dep:winit"]

[dependencies]
bytemuck = { version = "1", features = ["derive"] }
pollster = "0.4"
rne_math = { workspace = true }
rne_render = { workspace = true }
thiserror = { workspace = true }
wgpu = "24"
winit = { version = "0.30", optional = true }

[dev-dependencies]
naga = "24"
approx = "0.5"
rne_ecs = { workspace = true }
rne_urdf_import = { workspace = true }
rne_world = { workspace = true }
