[package]
name = "ssl_physics_coupling"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
rne_adapter_ssl = { workspace = true }
rne_ai = { workspace = true }

[[example]]
name = "87_ssl_physics_coupling"
path = "main.rs"
