[package]
name = "office_agv_shared_aisle"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
rne_ai = { workspace = true }

[[example]]
name = "85_office_agv_shared_aisle"
path = "main.rs"
