[package]
name = "latency_in_the_loop"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true
publish = false

[dependencies]
image = "0.25"
png = "0.17"
rne_ai = { path = "../../crates/rne_ai" }
rne_core = { path = "../../crates/rne_core" }
rne_data = { path = "../../crates/rne_data" }
rne_ecs = { path = "../../crates/rne_ecs" }
rne_math = { path = "../../crates/rne_math" }
rne_physics = { path = "../../crates/rne_physics" }
rne_render = { path = "../../crates/rne_render" }
rne_render_wgpu = { path = "../../crates/rne_render_wgpu" }
rne_robot = { path = "../../crates/rne_robot" }
rne_world = { path = "../../crates/rne_world" }

[[example]]
name = "51_latency_in_the_loop"
path = "main.rs"
