//! Physics events and queries.

use rne_ecs::Entity;
use rne_math::Vec3;
use serde::{Deserialize, Serialize};

/// One-step world-frame force and moment applied to a rigid body.
///
/// The force is applied at [`Self::point_world_m`], while [`Self::torque_world_nm`]
/// is a free moment about that same point. A backend must therefore preserve both
/// the direct moment and the moment generated by the force lever arm. Accepted
/// values affect exactly the next completed physics step and are then cleared.
/// This command is the backend-neutral output boundary for tire, aerodynamic,
/// disturbance, and other force-element models; it intentionally contains no
/// native physics-engine handles.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct ExternalBodyWrench {
    /// Dynamic rigid-body entity receiving the wrench.
    pub entity: Entity,
    /// Application point in world coordinates, in meters.
    pub point_world_m: Vec3,
    /// Force in world coordinates, in newtons.
    pub force_world_n: Vec3,
    /// Free moment in world coordinates about the application point, in newton-meters.
    pub torque_world_nm: Vec3,
}

impl ExternalBodyWrench {
    /// Returns whether every numeric component is finite.
    pub fn is_finite(self) -> bool {
        self.point_world_m.is_finite()
            && self.force_world_n.is_finite()
            && self.torque_world_nm.is_finite()
    }
}

/// Contact event between two colliders.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct ContactEvent {
    /// First colliding entity.
    pub entity_a: Entity,
    /// Second colliding entity.
    pub entity_b: Entity,
    /// Contact normal pointing from A to B, or zero for a sensor overlap.
    pub normal: Vec3,
    /// Accumulated normal-impulse magnitude for this contact pair over the last
    /// physics step, summed across every manifold and contact point between the
    /// two colliders (units: N·s, i.e. force integrated over the fixed step —
    /// Rapier applies impulses rather than forces internally). Zero when the
    /// backend does not populate it (e.g. a sensor overlap or contact pair with
    /// no active solver contact this step). Useful for distinguishing a light graze from a
    /// load-bearing contact (see friction-based grasping) without needing raw
    /// per-point solver data.
    pub impulse: f32,
}

/// Backend-neutral evidence for one solved contact point from the last step.
///
/// Entities are stored in ascending stable entity-index order. The normal points
/// from A to B, and [`Self::velocity_b_relative_to_a_world_m_s`] is the velocity
/// of B's surface minus A's surface at [`Self::point_world_m`]. The reported
/// normal force is a non-negative step-average magnitude; for impulse-based
/// solvers it is the solved normal impulse divided by the completed fixed-step
/// duration. Sensor overlaps are intentionally excluded.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct ContactPointSample {
    /// Canonically ordered first colliding entity.
    pub entity_a: Entity,
    /// Canonically ordered second colliding entity.
    pub entity_b: Entity,
    /// Contact point in world coordinates, in meters.
    pub point_world_m: Vec3,
    /// Unit contact normal pointing from A to B.
    pub normal_a_to_b: Vec3,
    /// Velocity of B relative to A at the contact point, in world coordinates.
    pub velocity_b_relative_to_a_world_m_s: Vec3,
    /// Non-negative average normal-force magnitude over the completed step, in newtons.
    pub normal_force_n: f64,
}

/// Raycast query definition.
#[derive(Clone, Copy, Debug, PartialEq, Serialize, Deserialize)]
pub struct RaycastQuery {
    /// Ray origin in meters.
    pub origin_m: Vec3,
    /// Unit ray direction.
    pub direction: Vec3,
    /// Maximum ray length in meters.
    pub max_distance_m: f64,
}

impl RaycastQuery {
    /// Creates a downward gravity-aligned ray used for ground checks.
    pub fn downward(origin_m: Vec3, max_distance_m: f64) -> Self {
        Self {
            origin_m,
            direction: Vec3::NEG_Y,
            max_distance_m,
        }
    }
}

/// Result of a successful raycast hit.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct RaycastHit {
    /// Hit entity.
    pub entity: Entity,
    /// Hit point in meters.
    pub point_m: Vec3,
    /// Surface normal at the hit point.
    pub normal: Vec3,
    /// Distance from the ray origin in meters.
    pub distance_m: f64,
}
