[package]
name = "external_urdf"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
rne_ai = { workspace = true }
rne_render = { workspace = true }

[[example]]
name = "35_external_urdf"
path = "main.rs"
