kind = "urdf"
model_name = "unitree_go2"

[urdf]
path = "go2_description/go2_description.rne.urdf"
base_body_type = "fixed"
initial_translation_m = [0.0, 0.36, 0.0]
initial_rotation_rpy = [-1.5707963267948966, 0.0, 0.0]
articulation = true
