[package]
name = "nav_elevation_icp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
rne_math = { workspace = true }
rne_nav = { workspace = true }
rne_slam = { workspace = true }

[[example]]
name = "100_nav_elevation_icp"
path = "main.rs"
