[package]
name = "render_clear"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
rne_render = { workspace = true }
rne_render_wgpu = { workspace = true }

[[example]]
name = "02_render_clear"
path = "main.rs"
