[package]
name = "rne_scenario_scale"
version = "0.2.0"
edition = "2021"
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[[bin]]
name = "rne-scenario-scale"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
rne_openscenario = { workspace = true }
rne_traffic = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
