[package]
name = "rne_scenario_scale"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "rne-scenario-scale"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
rne_openscenario = { workspace = true }
rne_traffic = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
