#!/usr/bin/env python3
"""Generate assets/robots/go2_description/go2_arm.rne.urdf.

Appends a generic 5-DOF arm with a two-finger parallel gripper to the welded
Go2's URDF (go2_description.rne.urdf): yaw, shoulder pitch, elbow pitch, wrist
pitch, wrist roll, and two prismatic fingers. It is not a specific product;
sizes and masses are chosen for a Go2-scale manipulator (1.46 kg in all) that can
reach a door knob 0.6 m above the floor and turn it.

    python3 tools/generate_go2_arm_urdf.py
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets/robots/go2_description/go2_description.rne.urdf"
OUTPUT = ROOT / "assets/robots/go2_description/go2_arm.rne.urdf"

UPPER_M = 0.28
FORE_M = 0.28
WRIST_M = 0.06
DARK = "0.16 0.17 0.19 1"
ALU = "0.72 0.74 0.78 1"
RUBBER = "0.12 0.12 0.12 1"


def box_inertia(m, a, b, c):
    return (m / 12 * (b * b + c * c), m / 12 * (a * a + c * c), m / 12 * (a * a + b * b))


def cyl_inertia(m, r, h):
    return (m / 12 * (3 * r * r + h * h), m / 12 * (3 * r * r + h * h), m / 2 * r * r)


def link(name, mass, com, inertia, visuals=(), collisions=()):
    ixx, iyy, izz = inertia
    return f"""  <link name="{name}">
    <inertial>
      <origin xyz="{com}" rpy="0 0 0"/>
      <mass value="{mass}"/>
      <inertia ixx="{ixx:.6f}" ixy="0" ixz="0" iyy="{iyy:.6f}" iyz="0" izz="{izz:.6f}"/>
    </inertial>
{''.join(visuals)}{''.join(collisions)}  </link>
"""


def vis(origin, geom, color, rpy="0 0 0"):
    return f"""    <visual>
      <origin xyz="{origin}" rpy="{rpy}"/>
      <geometry>{geom}</geometry>
      <material name="arm"><color rgba="{color}"/></material>
    </visual>
"""


def col(origin, geom, rpy="0 0 0"):
    return f"""    <collision>
      <origin xyz="{origin}" rpy="{rpy}"/>
      <geometry>{geom}</geometry>
    </collision>
"""


def joint(name, kind, parent, child, origin, axis=None, limit=None):
    axis_xml = f'\n    <axis xyz="{axis}"/>' if axis else ""
    limit_xml = (
        f'\n    <limit lower="{limit[0]}" upper="{limit[1]}" effort="{limit[2]}" velocity="{limit[3]}"/>'
        if limit
        else ""
    )
    return f"""  <joint name="{name}" type="{kind}">
    <origin xyz="{origin}" rpy="0 0 0"/>
    <parent link="{parent}"/>
    <child link="{child}"/>{axis_xml}{limit_xml}
  </joint>
"""


def arm():
    out = (
        "  <!-- A generic 5-DOF arm with a two-finger gripper, 1.46 kg in all: yaw,\n"
        "       shoulder, elbow and wrist pitch, wrist roll, and two prismatic fingers.\n"
        "       Not a specific product. Generated by tools/generate_go2_arm_urdf.py. -->\n"
    )
    out += link(
        "arm_mount", 0.25, "0 0 0.04", cyl_inertia(0.25, 0.045, 0.08),
        [vis("0 0 0.04", '<cylinder radius="0.045" length="0.08"/>', DARK)],
        [col("0 0 0.04", '<cylinder radius="0.045" length="0.08"/>')],
    )
    out += joint("arm_mount_joint", "fixed", "base", "arm_mount", "0.05 0 0.057")
    out += link(
        "arm_yaw", 0.25, "0 0 0.03", cyl_inertia(0.25, 0.04, 0.06),
        [vis("0 0 0.03", '<cylinder radius="0.04" length="0.06"/>', ALU)],
    )
    out += joint("arm_yaw_joint", "revolute", "arm_mount", "arm_yaw", "0 0 0.08", "0 0 1", (-2.0, 2.0, 10.0, 3.0))
    out += link(
        "arm_upper", 0.35, f"{UPPER_M / 2} 0 0", box_inertia(0.35, UPPER_M, 0.05, 0.05),
        [
            vis(f"{UPPER_M / 2} 0 0", f'<box size="{UPPER_M} 0.05 0.05"/>', ALU),
            vis("0 0 0", '<cylinder radius="0.035" length="0.07"/>', DARK, "1.5707963 0 0"),
        ],
        [col(f"{UPPER_M / 2 + 0.03} 0 0", f'<box size="{UPPER_M - 0.06} 0.05 0.05"/>')],
    )
    out += joint("arm_shoulder_joint", "revolute", "arm_yaw", "arm_upper", "0 0 0.06", "0 1 0", (-1.8, 1.6, 20.0, 3.0))
    out += link(
        "arm_fore", 0.25, f"{FORE_M / 2} 0 0", box_inertia(0.25, FORE_M, 0.04, 0.04),
        [
            vis(f"{FORE_M / 2} 0 0", f'<box size="{FORE_M} 0.04 0.04"/>', ALU),
            vis("0 0 0", '<cylinder radius="0.03" length="0.06"/>', DARK, "1.5707963 0 0"),
        ],
        [col(f"{FORE_M / 2} 0 0", f'<box size="{FORE_M - 0.04} 0.04 0.04"/>')],
    )
    out += joint("arm_elbow_joint", "revolute", "arm_upper", "arm_fore", f"{UPPER_M} 0 0", "0 1 0", (-2.7, 2.7, 12.0, 3.0))
    # Wrist pitch carries the roll motor.
    out += link(
        "arm_wrist", 0.15, f"{WRIST_M / 2} 0 0", cyl_inertia(0.15, 0.025, WRIST_M),
        [vis(f"{WRIST_M / 2} 0 0", f'<cylinder radius="0.025" length="{WRIST_M}"/>', DARK, "0 1.5707963 0")],
    )
    out += joint("arm_wrist_joint", "revolute", "arm_fore", "arm_wrist", f"{FORE_M} 0 0", "0 1 0", (-1.9, 1.9, 5.0, 3.0))
    # Wrist roll turns the hand about the arm's axis, which is how the knob turns.
    out += link(
        "arm_hand", 0.15, "0.025 0 0", box_inertia(0.15, 0.05, 0.10, 0.05),
        [vis("0.025 0 0", '<box size="0.05 0.10 0.05"/>', ALU)],
        [col("0.025 0 0", '<box size="0.05 0.10 0.05"/>')],
    )
    out += joint("arm_roll_joint", "revolute", "arm_wrist", "arm_hand", f"{WRIST_M} 0 0", "1 0 0", (-2.0, 2.0, 5.0, 4.0))
    # Fingers slide apart along the hand's y axis; each is 0 at the centre line and
    # opens to 0.04 m, so the jaw opens 0.08 m.
    for side, sign in (("left", 1), ("right", -1)):
        name = f"arm_finger_{side}"
        out += link(
            name, 0.03, f"0.025 {sign * 0.006} 0", box_inertia(0.03, 0.05, 0.012, 0.03),
            [vis(f"0.025 {sign * 0.006} 0", '<box size="0.05 0.012 0.03"/>', RUBBER)],
            [col(f"0.025 {sign * 0.006} 0", '<box size="0.05 0.012 0.03"/>')],
        )
        out += joint(
            f"arm_finger_{side}_joint", "prismatic", "arm_hand", name, "0.05 0 0",
            f"0 {sign} 0", (0.0, 0.04, 40.0, 0.2),
        )
    return out


def main():
    source = SOURCE.read_text()
    assert source.rstrip().endswith("</robot>")
    OUTPUT.write_text(source.rstrip()[: -len("</robot>")] + arm() + "</robot>\n")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
