[package]
name = "mobile_clutter_pick_place_e2e"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
rne_ai = { workspace = true }

[[example]]
name = "34_mobile_clutter_pick_place_e2e"
path = "main.rs"
