[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
bevy_ecs = { workspace = true }
rne_core = { workspace = true }
rne_ecs = { workspace = true }
rne_math = { workspace = true }
rne_world = { workspace = true }

[[example]]
name = "00_hello_world"
path = "main.rs"
