//! Plugin authoring scaffolds.
//!
//! [`scaffold_controller_plugin`] generates a complete, compilable controller
//! plugin crate (a `cdylib` implementing the versioned controller-plugin C ABI
//! from [`crate::cabi`]), a vendored [`rne_plugin_sdk`] module, and a
//! [`crate::PluginManifest`], so third-party authors can start from a working
//! shared library instead of a blank page or online dependency.

use crate::PluginManifest;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};

const CONTRACT_FILE: &str = "rne-scaffold.json";
const MAX_SCAFFOLD_FILE_BYTES: u64 = 16 * 1024 * 1024;
const SCAFFOLD_FILES: [&str; 4] = [
    "Cargo.toml",
    "src/rne_plugin_sdk.rs",
    "src/lib.rs",
    "rne-plugin.json",
];

/// Stable controller-plugin scaffold contract discriminator.
pub const CONTROLLER_PLUGIN_SCAFFOLD_CONTRACT_KIND: &str =
    "rne_controller_plugin_scaffold_contract";
/// Oldest controller-plugin scaffold schema retained by this reader.
pub const CONTROLLER_PLUGIN_SCAFFOLD_MIN_SCHEMA_VERSION: u32 = 1;
/// Current controller-plugin scaffold contract and generator schema.
pub const CONTROLLER_PLUGIN_SCAFFOLD_SCHEMA_VERSION: u32 = 1;

/// One exact file generated by a controller-plugin scaffold schema.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ControllerPluginScaffoldFile {
    /// Portable path relative to the scaffold root.
    pub path: String,
    /// Exact generated byte length.
    pub byte_length: u64,
    /// SHA-256 of exact generated bytes, with a `sha256:` prefix.
    pub sha256: String,
}

/// Self-describing, content-addressed controller-plugin authoring scaffold.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ControllerPluginScaffoldContract {
    /// Stable [`CONTROLLER_PLUGIN_SCAFFOLD_CONTRACT_KIND`] discriminator.
    pub kind: String,
    /// Retained generator and contract schema.
    pub schema_version: u32,
    /// Plugin and crate identifier embedded in generated files.
    pub plugin_name: String,
    /// Exact ordered set of generated files other than this manifest.
    pub files: Vec<ControllerPluginScaffoldFile>,
}

impl ControllerPluginScaffoldContract {
    /// Reads and strictly validates a scaffold contract from JSON bytes.
    pub fn from_json_slice(bytes: &[u8]) -> Result<Self, ScaffoldError> {
        let contract: Self = serde_json::from_slice(bytes)?;
        contract.validate()?;
        Ok(contract)
    }

    /// Validates schema, identity, file order, bounds, and digests.
    pub fn validate(&self) -> Result<(), ScaffoldError> {
        if self.kind != CONTROLLER_PLUGIN_SCAFFOLD_CONTRACT_KIND {
            return Err(ScaffoldError::Contract(format!(
                "scaffold kind must be {CONTROLLER_PLUGIN_SCAFFOLD_CONTRACT_KIND:?}"
            )));
        }
        if self.schema_version != 1 {
            return Err(unsupported_schema(self.schema_version));
        }
        validate_plugin_name(&self.plugin_name)?;
        if self.files.len() != SCAFFOLD_FILES.len() {
            return Err(ScaffoldError::Contract(format!(
                "controller scaffold contract must contain exactly {} generated files",
                SCAFFOLD_FILES.len()
            )));
        }
        for (file, expected_path) in self.files.iter().zip(SCAFFOLD_FILES) {
            if file.path != expected_path
                || file.byte_length == 0
                || file.byte_length > MAX_SCAFFOLD_FILE_BYTES
                || !valid_sha256(&file.sha256)
            {
                return Err(ScaffoldError::Contract(format!(
                    "invalid controller scaffold file contract for {expected_path}"
                )));
            }
        }
        Ok(())
    }

    /// Verifies one generated directory without following symlinks.
    pub fn validate_directory(&self, directory: &Path) -> Result<(), ScaffoldError> {
        self.validate()?;
        validate_directory_entries(
            directory,
            &["Cargo.toml", "rne-plugin.json", CONTRACT_FILE],
            &["src"],
        )?;
        validate_directory_entries(
            &directory.join("src"),
            &["lib.rs", "rne_plugin_sdk.rs"],
            &[],
        )?;
        for file in &self.files {
            let path = directory.join(&file.path);
            let bytes = fs::read(&path).map_err(|error| read_error(&path, error))?;
            if bytes.len() as u64 != file.byte_length || sha256(&bytes) != file.sha256 {
                return Err(ScaffoldError::Contract(format!(
                    "controller scaffold file {} differs from its contract",
                    file.path
                )));
            }
        }
        let contract_path = directory.join(CONTRACT_FILE);
        let actual = fs::read(&contract_path).map_err(|error| read_error(&contract_path, error))?;
        if actual != self.to_json_pretty()?.as_bytes() {
            return Err(ScaffoldError::Contract(
                "controller scaffold contract file is not canonical".to_string(),
            ));
        }
        Ok(())
    }

    /// Serializes canonical pretty JSON with a trailing newline.
    pub fn to_json_pretty(&self) -> Result<String, ScaffoldError> {
        self.validate()?;
        let mut text = serde_json::to_string_pretty(self)?;
        text.push('\n');
        Ok(text)
    }
}

/// Scaffold validation or I/O failure.
#[derive(Debug, thiserror::Error)]
pub enum ScaffoldError {
    /// The plugin name is not a valid identifier.
    #[error("invalid plugin name `{name}`: use ASCII letters, digits, and underscores")]
    InvalidName {
        /// Requested plugin name.
        name: String,
    },
    /// The requested retained generator schema is unsupported.
    #[error("unsupported controller scaffold schema {requested}; supported range is {minimum}..={current}")]
    UnsupportedSchema {
        /// Rejected schema.
        requested: u32,
        /// Oldest retained schema.
        minimum: u32,
        /// Current schema.
        current: u32,
    },
    /// A scaffold file could not be written.
    #[error("write plugin scaffold {path}: {message}")]
    Write {
        /// File path.
        path: String,
        /// Underlying I/O error.
        message: String,
    },
    /// A scaffold directory or file could not be inspected.
    #[error("read plugin scaffold {path}: {message}")]
    Read {
        /// Failed path.
        path: String,
        /// Underlying I/O error.
        message: String,
    },
    /// The plugin directory already exists.
    #[error("plugin directory {path} already exists")]
    Exists {
        /// Existing directory path.
        path: String,
    },
    /// The scaffold manifest could not be serialized.
    #[error("serialize plugin manifest: {0}")]
    Manifest(#[from] crate::PluginError),
    /// The scaffold self-manifest could not be serialized or parsed.
    #[error("plugin scaffold contract JSON: {0}")]
    Json(#[from] serde_json::Error),
    /// A generated scaffold contract or directory is invalid.
    #[error("invalid plugin scaffold contract: {0}")]
    Contract(String),
}

/// Validates a plugin name for use as a crate name and ABI name.
pub fn validate_plugin_name(name: &str) -> Result<(), ScaffoldError> {
    if !name.is_empty()
        && name
            .chars()
            .all(|character| character.is_ascii_alphanumeric() || character == '_')
    {
        Ok(())
    } else {
        Err(ScaffoldError::InvalidName {
            name: name.to_string(),
        })
    }
}

/// Generates a compilable controller-plugin crate under `parent_dir/<name>`.
///
/// Creates `Cargo.toml`, `src/lib.rs` (a `cdylib` implementing the
/// controller-plugin C ABI, initially a velocity-servo policy), a vendored
/// `src/rne_plugin_sdk.rs`, `rne-plugin.json` (a versioned
/// [`crate::PluginManifest`]), and canonical `rne-scaffold.json`. Returns the
/// created crate directory. Errors if the directory already exists.
pub fn scaffold_controller_plugin(name: &str, parent_dir: &Path) -> Result<PathBuf, ScaffoldError> {
    scaffold_controller_plugin_for_schema(
        name,
        parent_dir,
        CONTROLLER_PLUGIN_SCAFFOLD_SCHEMA_VERSION,
    )
}

/// Generates a controller-plugin crate for one retained scaffold schema.
pub fn scaffold_controller_plugin_for_schema(
    name: &str,
    parent_dir: &Path,
    schema_version: u32,
) -> Result<PathBuf, ScaffoldError> {
    validate_plugin_name(name)?;
    let crate_dir = parent_dir.join(name);
    if crate_dir.exists() {
        return Err(ScaffoldError::Exists {
            path: crate_dir.display().to_string(),
        });
    }
    let contents = scaffold_contents_for_schema(name, schema_version)?;
    let contract = contract_from_contents(name, schema_version, &contents)?;
    fs::create_dir_all(crate_dir.join("src")).map_err(|error| ScaffoldError::Write {
        path: crate_dir.display().to_string(),
        message: error.to_string(),
    })?;
    for (path, contents) in contents {
        write_scaffold_file(&crate_dir.join(path), &contents)?;
    }
    write_scaffold_file(&crate_dir.join(CONTRACT_FILE), &contract.to_json_pretty()?)?;
    contract.validate_directory(&crate_dir)?;
    Ok(crate_dir)
}

/// Returns the exact contract for the current controller scaffold schema.
pub fn controller_plugin_scaffold_contract(
    name: &str,
) -> Result<ControllerPluginScaffoldContract, ScaffoldError> {
    controller_plugin_scaffold_contract_for_schema(name, CONTROLLER_PLUGIN_SCAFFOLD_SCHEMA_VERSION)
}

/// Returns the exact contract for one retained controller scaffold schema.
pub fn controller_plugin_scaffold_contract_for_schema(
    name: &str,
    schema_version: u32,
) -> Result<ControllerPluginScaffoldContract, ScaffoldError> {
    validate_plugin_name(name)?;
    let contents = scaffold_contents_for_schema(name, schema_version)?;
    contract_from_contents(name, schema_version, &contents)
}

fn scaffold_contents_for_schema(
    name: &str,
    schema_version: u32,
) -> Result<Vec<(&'static str, String)>, ScaffoldError> {
    match schema_version {
        1 => scaffold_contents_v1(name),
        unsupported => Err(unsupported_schema(unsupported)),
    }
}

fn scaffold_contents_v1(name: &str) -> Result<Vec<(&'static str, String)>, ScaffoldError> {
    let manifest = PluginManifest::controller(name);
    let manifest_json = format!("{}\n", manifest.to_json()?);
    Ok(vec![
        ("Cargo.toml", cargo_manifest(name)),
        (
            "src/rne_plugin_sdk.rs",
            rne_plugin_sdk::RNE_PLUGIN_SDK_RUST_SOURCE.to_string(),
        ),
        ("src/lib.rs", lib_source(name)),
        ("rne-plugin.json", manifest_json),
    ])
}

fn contract_from_contents(
    name: &str,
    schema_version: u32,
    contents: &[(&str, String)],
) -> Result<ControllerPluginScaffoldContract, ScaffoldError> {
    let contract = ControllerPluginScaffoldContract {
        kind: CONTROLLER_PLUGIN_SCAFFOLD_CONTRACT_KIND.to_string(),
        schema_version,
        plugin_name: name.to_string(),
        files: contents
            .iter()
            .map(|(path, contents)| ControllerPluginScaffoldFile {
                path: (*path).to_string(),
                byte_length: contents.len() as u64,
                sha256: sha256(contents.as_bytes()),
            })
            .collect(),
    };
    contract.validate()?;
    Ok(contract)
}

fn unsupported_schema(requested: u32) -> ScaffoldError {
    ScaffoldError::UnsupportedSchema {
        requested,
        minimum: CONTROLLER_PLUGIN_SCAFFOLD_MIN_SCHEMA_VERSION,
        current: CONTROLLER_PLUGIN_SCAFFOLD_SCHEMA_VERSION,
    }
}

fn read_error(path: &Path, error: std::io::Error) -> ScaffoldError {
    ScaffoldError::Read {
        path: path.display().to_string(),
        message: error.to_string(),
    }
}

fn sha256(bytes: &[u8]) -> String {
    format!("sha256:{:x}", Sha256::digest(bytes))
}

fn valid_sha256(value: &str) -> bool {
    value.strip_prefix("sha256:").is_some_and(|hex| {
        hex.len() == 64
            && hex
                .bytes()
                .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
    })
}

fn validate_directory_entries(
    directory: &Path,
    expected_files: &[&str],
    expected_directories: &[&str],
) -> Result<(), ScaffoldError> {
    let metadata = fs::symlink_metadata(directory).map_err(|error| read_error(directory, error))?;
    if !metadata.file_type().is_dir() {
        return Err(ScaffoldError::Contract(format!(
            "scaffold path {} is not a real directory",
            directory.display()
        )));
    }
    let expected = expected_files
        .iter()
        .chain(expected_directories)
        .copied()
        .collect::<BTreeSet<_>>();
    let mut actual = BTreeSet::new();
    for entry in fs::read_dir(directory).map_err(|error| read_error(directory, error))? {
        let entry = entry.map_err(|error| read_error(directory, error))?;
        let name = entry.file_name().into_string().map_err(|_| {
            ScaffoldError::Contract("scaffold contains a non-Unicode file name".to_string())
        })?;
        let file_type = entry
            .file_type()
            .map_err(|error| read_error(&entry.path(), error))?;
        if file_type.is_symlink() {
            return Err(ScaffoldError::Contract(format!(
                "scaffold entry {} must not be a symlink",
                entry.path().display()
            )));
        }
        let expected_file = expected_files.contains(&name.as_str());
        let expected_directory = expected_directories.contains(&name.as_str());
        if (expected_file && !file_type.is_file())
            || (expected_directory && !file_type.is_dir())
            || (!expected_file && !expected_directory)
        {
            return Err(ScaffoldError::Contract(format!(
                "unexpected scaffold entry {}",
                entry.path().display()
            )));
        }
        actual.insert(name);
    }
    let actual = actual.iter().map(String::as_str).collect::<BTreeSet<_>>();
    if actual != expected {
        return Err(ScaffoldError::Contract(format!(
            "scaffold directory {} does not contain the exact retained file set",
            directory.display()
        )));
    }
    Ok(())
}

fn write_scaffold_file(path: &Path, contents: &str) -> Result<(), ScaffoldError> {
    fs::write(path, contents).map_err(|error| ScaffoldError::Write {
        path: path.display().to_string(),
        message: error.to_string(),
    })
}

fn cargo_manifest(name: &str) -> String {
    format!(
        r#"[package]
name = "{name}"
description = "RNE controller plugin scaffold"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib", "lib"]

# Standalone workspace root so `cargo build` here never resolves against an
# enclosing workspace.
[workspace]
"#
    )
}

fn lib_source(name: &str) -> String {
    format!(
        r#"//! RNE controller plugin `{name}`.
//!
//! This scaffold compiles to a shared library implementing the versioned
//! controller-plugin C ABI (`rne_plugin::cabi`, ABI version 3). Replace the
//! velocity-servo policy in `rne_controller_step_v3` with your controller.

use std::ffi::{{c_char, c_void, CStr, CString}};
// The vendored SDK intentionally contains the complete ABI while this example
// uses only one capability subset.
#[allow(dead_code)]
mod rne_plugin_sdk;
use rne_plugin_sdk::{{
    RneControllerStepResultV3, RneJointObservationV3, RneJointPosition, RneJointVelocity,
    RneJointVelocityV3, RNE_CONTROLLER_CAP_JOINT_POSITION_OBSERVATION,
    RNE_CONTROLLER_CAP_JOINT_VELOCITY_COMMAND, RNE_CONTROLLER_CAP_MULTI_ROBOT,
    RNE_PLUGIN_ABI_VERSION,
}};

/// ABI version implemented by this plugin.
pub const ABI_VERSION: u32 = RNE_PLUGIN_ABI_VERSION;

/// Logical plugin name reported through [`rne_plugin_name`].
pub const PLUGIN_NAME: &str = "{name}";

const CAPABILITIES: u64 = RNE_CONTROLLER_CAP_JOINT_POSITION_OBSERVATION
    | RNE_CONTROLLER_CAP_JOINT_VELOCITY_COMMAND
    | RNE_CONTROLLER_CAP_MULTI_ROBOT;

/// Controller state owned by the plugin.
struct ControllerState {{
    name: CString,
    target_rad: f64,
    gain: f64,
    max_velocity_rad_s: f64,
    configured: bool,
    active: bool,
    shutdown: bool,
}}

static PLUGIN_NAME_C: &[u8] = b"{name}\0";

/// Reports the ABI version this plugin was built against.
#[no_mangle]
pub extern "C" fn rne_plugin_abi_version() -> u32 {{
    ABI_VERSION
}}

/// Reports the plugin's logical name as a static NUL-terminated UTF-8 string.
#[no_mangle]
pub extern "C" fn rne_plugin_name() -> *const c_char {{
    PLUGIN_NAME_C.as_ptr().cast()
}}

/// Reports the supported ABI-v3 capability mask.
#[no_mangle]
pub extern "C" fn rne_plugin_capabilities() -> u64 {{
    CAPABILITIES
}}

/// Creates a controller instance.
///
/// Returns a non-null opaque handle on success, or null after writing a
/// message into `error` (if non-null with capacity) on failure.
///
/// # Safety
///
/// `joint` must be null or point to a NUL-terminated UTF-8 string. `error`
/// must be null or point to a buffer of `error_capacity` bytes.
#[no_mangle]
pub unsafe extern "C" fn rne_controller_create(
    joint: *const c_char,
    target_rad: f64,
    gain: f64,
    max_velocity_rad_s: f64,
    error: *mut c_char,
    error_capacity: usize,
) -> *mut c_void {{
    if joint.is_null() {{
        write_error(error, error_capacity, "joint must not be null");
        return std::ptr::null_mut();
    }}
    let Ok(joint) = (|| -> Result<String, ()> {{
        // SAFETY: `joint` is a valid NUL-terminated string by contract.
        let joint = unsafe {{ CStr::from_ptr(joint) }}.to_str().map_err(|_| ())?;
        if joint.is_empty() {{
            return Err(());
        }}
        if !target_rad.is_finite() || !gain.is_finite() || !max_velocity_rad_s.is_finite() {{
            return Err(());
        }}
        if gain < 0.0 || max_velocity_rad_s < 0.0 {{
            return Err(());
        }}
        Ok(joint.to_string())
    }})() else {{
        write_error(error, error_capacity, "invalid create parameters");
        return std::ptr::null_mut();
    }};
    let name = match CString::new(joint) {{
        Ok(name) => name,
        Err(_) => {{
            write_error(error, error_capacity, "joint contains a NUL byte");
            return std::ptr::null_mut();
        }}
    }};
    let state = Box::new(ControllerState {{
        name,
        target_rad,
        gain,
        max_velocity_rad_s,
        configured: false,
        active: false,
        shutdown: false,
    }});
    Box::into_raw(state).cast::<c_void>()
}}

/// Destroys a controller instance created by `rne_controller_create`.
///
/// # Safety
///
/// `handle` must be a non-null pointer returned by `rne_controller_create`
/// and not already destroyed.
#[no_mangle]
pub unsafe extern "C" fn rne_controller_destroy(handle: *mut c_void) {{
    if handle.is_null() {{
        return;
    }}
    // SAFETY: `handle` is a unique live instance by contract.
    drop(unsafe {{ Box::from_raw(handle.cast::<ControllerState>()) }});
}}

/// Computes velocity commands for the current joint observations.
///
/// Returns the number of commands written into `output` (at most one: the
/// commanded joint), and writes at most `output_capacity` entries.
///
/// # Safety
///
/// `handle` must be a live instance, `observations` must point to
/// `observation_count` valid entries with NUL-terminated names, and `output`
/// must point to a buffer of `output_capacity` entries.
#[no_mangle]
pub unsafe extern "C" fn rne_controller_step(
    handle: *const c_void,
    observations: *const RneJointPosition,
    observation_count: usize,
    output: *mut RneJointVelocity,
    output_capacity: usize,
) -> usize {{
    if output_capacity == 0 {{
        return 0;
    }}
    // SAFETY: the handle and input array satisfy the callback contract.
    let state = unsafe {{ &*handle.cast::<ControllerState>() }};
    let observations = unsafe {{ std::slice::from_raw_parts(observations, observation_count) }};
    for observation in observations {{
        if observation.name.is_null() {{
            continue;
        }}
        // SAFETY: observation names are NUL-terminated by contract.
        if unsafe {{ CStr::from_ptr(observation.name) }}.to_bytes() != state.name.to_bytes() {{
            continue;
        }}
        let velocity = (state.gain * (state.target_rad - observation.position_rad))
            .clamp(-state.max_velocity_rad_s, state.max_velocity_rad_s);
        // SAFETY: output capacity is non-zero and the state-owned name remains
        // valid until instance destruction.
        unsafe {{
            *output = RneJointVelocity {{
                name: state.name.as_ptr(),
                velocity_rad_s: velocity,
            }}
        }};
        return 1;
    }}
    0
}}

/// Accepts the host's negotiated ABI-v3 capability requirements.
///
/// # Safety
///
/// `handle` must be a live instance and `error` must be null or point to
/// `error_capacity` writable bytes.
#[no_mangle]
pub unsafe extern "C" fn rne_controller_configure_v3(
    handle: *mut c_void,
    required_capabilities: u64,
    error: *mut c_char,
    error_capacity: usize,
) -> i32 {{
    // SAFETY: `handle` is a live instance by contract.
    let state = unsafe {{ &mut *handle.cast::<ControllerState>() }};
    if state.shutdown {{
        write_error(error, error_capacity, "controller is shut down");
        return 1;
    }}
    if required_capabilities & !CAPABILITIES != 0 {{
        write_error(error, error_capacity, "unsupported required capability");
        return 1;
    }}
    state.configured = true;
    0
}}

/// Activates or resets one deterministic ABI-v3 episode.
///
/// # Safety
///
/// `handle` must be a live instance and `error` must be null or point to
/// `error_capacity` writable bytes.
#[no_mangle]
pub unsafe extern "C" fn rne_controller_reset_v3(
    handle: *mut c_void,
    _episode: u64,
    _seed: u64,
    _step: u64,
    _sim_time_ticks: u64,
    error: *mut c_char,
    error_capacity: usize,
) -> i32 {{
    // SAFETY: `handle` is a live instance by contract.
    let state = unsafe {{ &mut *handle.cast::<ControllerState>() }};
    if !state.configured || state.shutdown {{
        write_error(
            error,
            error_capacity,
            "controller must be configured and not shut down",
        );
        return 1;
    }}
    state.active = true;
    0
}}

/// Computes robot-scoped velocity commands for one ABI-v3 fixed step.
///
/// # Safety
///
/// `handle` must be a live instance, `observations` and `output` must point to
/// arrays of their declared lengths, identifiers must be NUL-terminated, and
/// `error` must be null or point to `error_capacity` writable bytes.
#[no_mangle]
pub unsafe extern "C" fn rne_controller_step_v3(
    handle: *mut c_void,
    _step: u64,
    _sim_time_ticks: u64,
    observations: *const RneJointObservationV3,
    observation_count: usize,
    output: *mut RneJointVelocityV3,
    output_capacity: usize,
    error: *mut c_char,
    error_capacity: usize,
) -> RneControllerStepResultV3 {{
    // SAFETY: `handle` is a live instance by contract.
    let state = unsafe {{ &mut *handle.cast::<ControllerState>() }};
    if !state.active || state.shutdown {{
        write_error(error, error_capacity, "controller is not active");
        return RneControllerStepResultV3 {{
            status: 1,
            output_count: 0,
        }};
    }}
    // SAFETY: the host supplies an array with the declared length.
    let observations = unsafe {{ std::slice::from_raw_parts(observations, observation_count) }};
    let mut output_count = 0;
    for observation in observations {{
        if observation.robot_id.is_null() || observation.name.is_null() {{
            continue;
        }}
        // SAFETY: observation names are NUL-terminated by contract.
        if unsafe {{ CStr::from_ptr(observation.name) }}.to_bytes() != state.name.to_bytes() {{
            continue;
        }}
        if output_count >= output_capacity {{
            write_error(error, error_capacity, "output capacity is too small");
            return RneControllerStepResultV3 {{
                status: 1,
                output_count: 0,
            }};
        }}
        let velocity = (state.gain * (state.target_rad - observation.position_rad))
            .clamp(-state.max_velocity_rad_s, state.max_velocity_rad_s);
        // SAFETY: `output_count < output_capacity`; both pointers stay valid
        // until the host copies the result immediately after this call.
        unsafe {{
            *output.add(output_count) = RneJointVelocityV3 {{
                robot_id: observation.robot_id,
                name: state.name.as_ptr(),
                velocity_rad_s: velocity,
            }}
        }};
        output_count += 1;
    }}
    RneControllerStepResultV3 {{
        status: 0,
        output_count,
    }}
}}

/// Terminates the ABI-v3 lifecycle before instance destruction.
///
/// # Safety
///
/// `handle` must be a live instance and `error` must be null or point to
/// `error_capacity` writable bytes.
#[no_mangle]
pub unsafe extern "C" fn rne_controller_shutdown_v3(
    handle: *mut c_void,
    error: *mut c_char,
    error_capacity: usize,
) -> i32 {{
    // SAFETY: `handle` is a live instance by contract.
    let state = unsafe {{ &mut *handle.cast::<ControllerState>() }};
    if state.shutdown {{
        write_error(error, error_capacity, "controller is already shut down");
        return 1;
    }}
    state.active = false;
    state.shutdown = true;
    0
}}

/// Writes a NUL-terminated message into `error` when it has capacity.
///
/// # Safety
///
/// `error` must be null or point to a buffer of `error_capacity` bytes.
unsafe fn write_error(error: *mut c_char, error_capacity: usize, message: &str) {{
    if error.is_null() || error_capacity == 0 {{
        return;
    }}
    let bytes = message.as_bytes();
    let length = bytes.len().min(error_capacity - 1);
    // SAFETY: `length + 1` fits the declared caller-owned buffer.
    unsafe {{
        std::ptr::copy_nonoverlapping(bytes.as_ptr().cast::<c_char>(), error, length);
        *error.add(length) = 0;
    }}
}}
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    #[test]
    fn scaffolds_a_compilable_crate() {
        let parent = std::env::temp_dir().join("rne-scaffold-test");
        let _ = fs::remove_dir_all(&parent);
        let name = "my_controller";
        let crate_dir = scaffold_controller_plugin(name, &parent).expect("scaffold");

        assert!(crate_dir.join("Cargo.toml").exists());
        assert!(crate_dir.join("src/lib.rs").exists());
        assert!(crate_dir.join("src/rne_plugin_sdk.rs").exists());
        let manifest_path = crate_dir.join("rne-plugin.json");
        assert!(manifest_path.exists());
        let contract_path = crate_dir.join(CONTRACT_FILE);
        assert!(contract_path.exists());
        let contract = ControllerPluginScaffoldContract::from_json_slice(
            &fs::read(&contract_path).expect("read scaffold contract"),
        )
        .expect("parse scaffold contract");
        assert_eq!(contract.plugin_name, name);
        assert_eq!(contract.schema_version, 1);
        contract
            .validate_directory(&crate_dir)
            .expect("validate scaffold directory");
        let manifest_text = fs::read_to_string(&manifest_path).expect("read manifest");
        let manifest: crate::PluginManifest =
            serde_json::from_str(&manifest_text).expect("parse manifest");
        assert_eq!(manifest.name, name);

        let lib = fs::read_to_string(crate_dir.join("src/lib.rs")).expect("read lib");
        for symbol in [
            "rne_plugin_abi_version",
            "rne_plugin_name",
            "rne_plugin_capabilities",
            "rne_controller_create",
            "rne_controller_destroy",
            "rne_controller_step",
            "rne_controller_configure_v3",
            "rne_controller_reset_v3",
            "rne_controller_step_v3",
            "rne_controller_shutdown_v3",
        ] {
            assert!(lib.contains(symbol), "lib.rs must export `{symbol}`");
        }
        assert!(lib.contains("pub const ABI_VERSION: u32 = RNE_PLUGIN_ABI_VERSION;"));
        assert!(lib.contains("mod rne_plugin_sdk;"));
        assert!(lib.contains(&format!("pub const PLUGIN_NAME: &str = \"{name}\";")));

        let sdk =
            fs::read_to_string(crate_dir.join("src/rne_plugin_sdk.rs")).expect("read vendored SDK");
        assert_eq!(sdk, rne_plugin_sdk::RNE_PLUGIN_SDK_RUST_SOURCE);

        let output_dir = parent.join("rustc-output");
        fs::create_dir_all(&output_dir).expect("create rustc output directory");
        let rustc = std::env::var_os("RUSTC").unwrap_or_else(|| "rustc".into());
        let status = std::process::Command::new(rustc)
            .arg("--edition=2021")
            .arg("--crate-type=lib")
            .arg("--out-dir")
            .arg(&output_dir)
            .arg(crate_dir.join("src/lib.rs"))
            .status()
            .expect("run rustc on generated plugin source");
        assert!(status.success(), "generated plugin source must compile");

        fs::write(crate_dir.join("unexpected.txt"), "unexpected\n")
            .expect("add unexpected scaffold file");
        assert!(matches!(
            contract.validate_directory(&crate_dir),
            Err(ScaffoldError::Contract(_))
        ));
        fs::remove_file(crate_dir.join("unexpected.txt")).expect("remove unexpected file");

        fs::write(crate_dir.join("src/lib.rs"), "// tampered\n").expect("tamper scaffold");
        assert!(matches!(
            contract.validate_directory(&crate_dir),
            Err(ScaffoldError::Contract(_))
        ));

        let _ = fs::remove_dir_all(&parent);
    }

    #[test]
    fn rejects_invalid_names_and_existing_directories() {
        assert!(matches!(
            validate_plugin_name(""),
            Err(ScaffoldError::InvalidName { .. })
        ));
        assert!(matches!(
            validate_plugin_name("my-plugin"),
            Err(ScaffoldError::InvalidName { .. })
        ));
        assert!(matches!(
            validate_plugin_name("a b"),
            Err(ScaffoldError::InvalidName { .. })
        ));
        assert!(validate_plugin_name("velocity_servo").is_ok());

        assert!(matches!(
            controller_plugin_scaffold_contract_for_schema("velocity_servo", 2),
            Err(ScaffoldError::UnsupportedSchema {
                requested: 2,
                minimum: 1,
                current: 1,
            })
        ));

        let parent = std::env::temp_dir().join("rne-scaffold-exists");
        let _ = fs::remove_dir_all(&parent);
        scaffold_controller_plugin("exists", &parent).expect("scaffold");
        assert!(matches!(
            scaffold_controller_plugin("exists", &parent),
            Err(ScaffoldError::Exists { .. })
        ));
        let _ = fs::remove_dir_all(&parent);
    }
}
