[package]
name = "g1_forward_stride"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
rne_ai = { workspace = true }
rne_math = { workspace = true }

[[example]]
name = "124_g1_forward_stride"
path = "main.rs"
