[package]
name = "mobile_manipulator_lift"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
rne_ai = { workspace = true }

[[example]]
name = "30_mobile_manipulator_lift"
path = "main.rs"
