[package]
name = "multi_robot_agent"
version = "0.2.0"
edition = "2021"
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
rne_ai = { workspace = true }
rne_math = { workspace = true }
rne_robot = { workspace = true }

[[example]]
name = "13_multi_robot_agent"
path = "main.rs"
